[tool.poetry]
name = "garmin-to-fittrackee"
version = "0.11.1"
description = "A simple script to synchronize garmin to fittrackee. Inspired by https://github.com/jat255/strava-to-fittrackee"
authors = ["Dryusdan <contact@dryusdan.fr>"]
license = "GPL-3"
readme = "README.md"
packages = [{include = "garmin_to_fittrackee"}]

[tool.poetry.scripts]
garmin2fittrackee = "garmin_to_fittrackee.main:app"

[tool.poetry.dependencies]
python = "^3.12"
typer = "^0.27.1"
garminconnect = "^0.3.11"
pendulum = "^3.2.0"
pyyaml = "^6.0.3"
requests = "^2.34.2"
requests-oauthlib = "^2.0.0"
packaging = "^26.3"


[tool.poetry.group.dev.dependencies]
ruff = "^0.16.4"
isort = "^8.0.1"



[tool.poetry.group.test.dependencies]
pytest = "^9.1.1"
pytest-mock = "^3.15.1"
requests-mock = "^1.12.1"
pytest-cov = "^7.1.0"
coverage = "^7.15.4"

[[tool.poetry.source]]
name = "forgejo"
url = "https://git.dryusdan.fr/api/packages/Dryusdan/pypi"
priority = "supplemental"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
]

[tool.ruff.format]
docstring-code-format = true

[tool.coverage.run]
omit = [
    "tests/*",
]
[tool.coverage.report]
fail_under = 90
