---
name: Development code quality
run-name: testdev
on:
  push:
    branches-ignore:
      - stable
      - main
    paths-ignore:
      - coverage.json
jobs:
  run-unittest:
    strategy:
      matrix:
        os:
          - python3.13
          - python3.12
          - python3.11
          - python3.10
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install test programm
        run: |
          . "${HOME}"/.cargo/env
          poetry install --with test
      - name: Run unit test
        run: poetry run pytest
