---
name: Development code quality
run-name: testdev
on:
  push:
    branches-ignore:
      - stable
      - main
    paths-ignore:
      - coverage.json
jobs:
  run-unittest:
    strategy:
      matrix:
        os:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
    runs-on: git.dryusdan.fr/dryusdan/python:${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install test programm
        run: |
          . "${HOME}"/.cargo/env
          poetry install --with test
      - name: Run unit test
        run: poetry run pytest
